import Head from 'next/head'
import React from 'react'
import Layout from '../Layout/Layout'

interface Props {

}

const Liked = (props: Props) => {
    return (
        <>
            <Head>
                <title>Bernau Liked</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                
            </Layout>
        </>
    )
}

export default Liked
